abbreviations = {"ak": "ạ",
                 "bt": "biết",
                 "bic": "biết",
                 "bíc": "biết",
                 "bik": "biết",
                 "bík": "biết",
                 "biếc": "biết",
                 "bth": "bình thường",
                 "bthg": "bình thường",
                 "cg": "cũng",
                 "ch": "chưa",
                 "cug": "cũng",
                 "cs": "có",
                 "cx":  "cũng",
                 "dc": "được",
                 "dth": "dễ thương",
                 "ddc": "được",
                 "đc": "được",
                 "đg": "đang",
                 "đỉm": "điểm",
                 "e": "em",
                 "gì z": "gì vậy",
                 "hok": "không",
                 "hong": "không",
                 "hông": "không",
                 "ik": "đi",
                 "ikk": "đi",
                 "í": "ấy",
                 "j": "gì",
                 "k": "không",
                 "kbt": "không biết",
                 "kco": "không có",
                 "kh": "không",
                 "khco": "không có",
                 "khs": "không hiểu sao",
                 "khum": "không",
                 "khôm": "không",
                 "ko": "không",
                 "k0": "không",
                 "lm": "làm",
                 "lun": "luôn",
                 "m": "mình",
                 "mik": "mình",
                 "mn": "mọi người",
                 "m.n": "mọi người",
                 "mng": "mọi người",
                 "ms": "mới",
                 "ncl": "nói chung",
                 "nchung": "nói chung",
                 "ng": "người",
                 "nhm": "nhưng mà",
                 "nhma": "nhưng mà",
                 "nma": "nhưng mà",
                 "nhưg": "nhưng",
                 "nhg": "nhưng",
                 "ns": "nói",
                 "nx": "nữa",
                 "oki": "ok",
                 "okii": "ok",
                 "okla": "ok",
                 "oke": "ok",
                 "okela": "ok",
                 "pk": "phải",
                 "qc": "quảng cáo",
                 "qcao": "quảng cáo",
                 "ql": "quay lại",
                 "qlai": "quay lại",
                 "r": "rồi",
                 "rùi": "rồi",
                 "sp": "sản phẩm",
                 "s": "sao",
                 "sd": "sử dụng",
                 "siu": "siêu",
                 "sop": "shop",
                 "socola": "chocolate",
                 "tc": "tính chất",
                 "tg": "thời gian",
                 "thíc": "thích",
                 "thik": "thích",
                 "thík": "thích",
                 "tht": "thật",
                 "thưn": "thương",
                 "tr": "trời",
                 "trc": "trước",
                 "v": "vậy",
                 "vd": "video",
                 "vid": "video",
                 "vs": "với",
                 "xg": "xong",
                 "ý": "ấy",
                 "z": "gì"}

common_typos = {"li": "lì",
                "duoc": "được",
                "đuoc": "được",
                "lun": "luôn",
                "mầu": "màu",
                "moi": "môi",
                "naof": "nào",
                "nhận xử": "nhận xu",
                "nhah": "nhanh",
                "nun": "luôn",
                "oi": "ơi",
                "sài": "xài",
                "tot": "tốt",
                "vở":"vỏ",
                "xểu": "xỉu"}

synonyms = {"mỏ": "môi",
            "mồm": "môi",
            "mõm": "môi",
            "sơn": "son"}
