abbreviations = {"ak": "ạ",
                 "bt": "biết",
                 "bic": "biết",
                 "bíc": "biết",
                 "bik": "biết",
                 "bík": "biết",
                 "biếc": "biết",
                 "bth": "bình thường",
                 "bthg": "bình thường",
                 "cg": "cũng",
                 "ch": "chưa",
                 "cug": "cũng",
                 "cs": "có",
                 "cx":  "cũng",
                 "dc": "được",
                 "dth": "dễ thương",
                 "đc": "được",
                 "đg": "đang",
                 "đỉm": "điểm",
                 "e": "em",
                 "gì z": "gì vậy",
                 "hok": "không",
                 "hong": "không",
                 "hông": "không",
                 "j": "gì",
                 "k": "không",
                 "kh": "không",
                 "khco": "không có",
                 "khs": "không hiểu sao",
                 "khum": "không",
                 "khôm": "không",
                 "lm": "làm",
                 "lun": "luôn",
                 "m": "mình",
                 "mik": "mình",
                 "mn": "mọi người",
                 "mng": "mọi người",
                 "ms": "mới",
                 "ncl": "nói chung",
                 "nchung": "nói chung",
                 "ng": "người",
                 "nhm": "nhưng mà",
                 "nhma": "nhưng mà",
                 "nma": "nhưng mà",
                 "nhưg": "nhưng",
                 "nhg": "nhưng",
                 "nx": "nữa",
                 "oki": "ok",
                 "okii": "ok",
                 "okla": "ok",
                 "okela": "ok",
                 "r": "rồi",
                 "rùi": "rồi",
                 "sp": "sản phẩm",
                 "s": "sao",
                 "sd": "sử dụng",
                 "siu": "siêu",
                 "sop": "shop",
                 "tc": "tính chất",
                 "tg": "thời gian",
                 "thíc": "thích",
                 "thik": "thích",
                 "thík": "thích",
                 "tr": "trời",
                 "trc": "trước",
                 "thưn": "thương",
                 "v": "vậy",
                 "vd": "video",
                 "vid": "video",
                 "vs": "với",
                 "z": "gì"}